# Generated by Django 5.2.15 on 2026-07-09 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('role_changed', 'role_changed'), ('user_blocked', 'user_blocked'), ('user_unblocked', 'user_unblocked'), ('record_invalidated', 'record_invalidated'), ('data_exported', 'data_exported'), ('safety_detail_viewed', 'safety_detail_viewed'), ('dashboard_viewed', 'dashboard_viewed'), ('visit_recorded', 'visit_recorded'), ('visit_corrected', 'visit_corrected'), ('visit_voided', 'visit_voided'), ('cheki_recorded', 'cheki_recorded'), ('cheki_corrected', 'cheki_corrected'), ('cheki_voided', 'cheki_voided'), ('safety_report_created', 'safety_report_created'), ('safety_report_status_changed', 'safety_report_status_changed'), ('safety_report_resolved', 'safety_report_resolved'), ('user_risk_flagged', 'user_risk_flagged'), ('schedule_created', 'schedule_created'), ('schedule_edited', 'schedule_edited'), ('schedule_published', 'schedule_published'), ('schedule_unpublished', 'schedule_unpublished'), ('schedule_change_requested', 'schedule_change_requested'), ('schedule_change_approved', 'schedule_change_approved'), ('schedule_change_rejected', 'schedule_change_rejected'), ('cast_profile_created', 'cast_profile_created'), ('cast_profile_updated', 'cast_profile_updated'), ('cast_consent_recorded', 'cast_consent_recorded'), ('pos_order_linked', 'pos_order_linked'), ('pos_order_voided', 'pos_order_voided'), ('reservation_created', 'reservation_created'), ('reservation_confirmed', 'reservation_confirmed'), ('reservation_changed', 'reservation_changed'), ('reservation_cancelled', 'reservation_cancelled'), ('reservation_no_show', 'reservation_no_show'), ('event_campaign_created', 'event_campaign_created'), ('event_campaign_updated', 'event_campaign_updated'), ('event_campaign_published', 'event_campaign_published'), ('event_campaign_unpublished', 'event_campaign_unpublished'), ('event_campaign_closed', 'event_campaign_closed'), ('guide_section_created', 'guide_section_created'), ('guide_section_updated', 'guide_section_updated'), ('guide_section_published', 'guide_section_published'), ('guide_section_unpublished', 'guide_section_unpublished'), ('coupon_issued', 'coupon_issued'), ('coupon_redeemed', 'coupon_redeemed'), ('coupon_cancelled', 'coupon_cancelled'), ('coupon_expired', 'coupon_expired'), ('point_granted', 'point_granted'), ('point_adjusted', 'point_adjusted'), ('refund_reviewed', 'refund_reviewed'), ('refund_accepted', 'refund_accepted'), ('refund_rejected', 'refund_rejected')], max_length=32)),
                ('target', models.CharField(max_length=255)),
                ('reason', models.CharField(blank=True, default='', max_length=512)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_entries', to='identity.account')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='audit_audit_action_ebedd2_idx'), models.Index(fields=['actor', 'created_at'], name='audit_audit_actor_i_3c2844_idx')],
            },
        ),
    ]
