# Generated by Django 6.0.7 on 2026-07-17 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditentry',
            name='action',
            field=models.CharField(choices=[('role_changed', 'role_changed'), ('user_blocked', 'user_blocked'), ('user_unblocked', 'user_unblocked'), ('record_invalidated', 'record_invalidated'), ('data_exported', 'data_exported'), ('safety_detail_viewed', 'safety_detail_viewed'), ('dashboard_viewed', 'dashboard_viewed'), ('visit_recorded', 'visit_recorded'), ('visit_corrected', 'visit_corrected'), ('visit_voided', 'visit_voided'), ('cheki_recorded', 'cheki_recorded'), ('cheki_corrected', 'cheki_corrected'), ('cheki_voided', 'cheki_voided'), ('safety_report_created', 'safety_report_created'), ('safety_report_status_changed', 'safety_report_status_changed'), ('safety_report_resolved', 'safety_report_resolved'), ('user_risk_flagged', 'user_risk_flagged'), ('schedule_created', 'schedule_created'), ('schedule_edited', 'schedule_edited'), ('schedule_published', 'schedule_published'), ('schedule_unpublished', 'schedule_unpublished'), ('schedule_change_requested', 'schedule_change_requested'), ('schedule_change_approved', 'schedule_change_approved'), ('schedule_change_rejected', 'schedule_change_rejected'), ('cast_profile_created', 'cast_profile_created'), ('cast_profile_updated', 'cast_profile_updated'), ('cast_consent_recorded', 'cast_consent_recorded'), ('pos_order_linked', 'pos_order_linked'), ('pos_order_voided', 'pos_order_voided'), ('reservation_created', 'reservation_created'), ('reservation_confirmed', 'reservation_confirmed'), ('reservation_changed', 'reservation_changed'), ('reservation_cancelled', 'reservation_cancelled'), ('reservation_no_show', 'reservation_no_show'), ('event_campaign_created', 'event_campaign_created'), ('event_campaign_updated', 'event_campaign_updated'), ('event_campaign_published', 'event_campaign_published'), ('event_campaign_unpublished', 'event_campaign_unpublished'), ('event_campaign_closed', 'event_campaign_closed'), ('guide_section_created', 'guide_section_created'), ('guide_section_updated', 'guide_section_updated'), ('guide_section_published', 'guide_section_published'), ('guide_section_unpublished', 'guide_section_unpublished'), ('coupon_issued', 'coupon_issued'), ('coupon_redeemed', 'coupon_redeemed'), ('coupon_cancelled', 'coupon_cancelled'), ('coupon_expired', 'coupon_expired'), ('point_granted', 'point_granted'), ('point_adjusted', 'point_adjusted'), ('refund_reviewed', 'refund_reviewed'), ('refund_accepted', 'refund_accepted'), ('refund_rejected', 'refund_rejected'), ('upload_taken_down', 'upload_taken_down')], max_length=32),
        ),
    ]
