// Material Design 아이콘 중앙 레지스트리 (react-icons/md). 시맨틱 별칭으로 re-export.
// 컴포넌트는 여기서 import. react-icons는 currentColor + className(size-* CSS) 호환.
// 참고 메모리: assen-icons-material.
export {
  MdHome as HomeIcon,
  MdDynamicFeed as FeedIcon,
  MdStorefront as StoreIcon,
  MdFavoriteBorder as HeartIcon,
  MdFavorite as HeartFilledIcon,
  MdSearch as SearchIcon,
  MdSearchOff as SearchOffIcon,
  MdNotificationsNone as BellIcon,
  MdMoreHoriz as MoreIcon,
  MdChevronRight as ChevronRightIcon,
  MdChevronLeft as ChevronLeftIcon,
  MdCalendarToday as CalendarIcon,
  MdExpandMore as ExpandMoreIcon,
  MdCheck as CheckIcon,
  MdClose as CloseIcon,
  MdChatBubbleOutline as CommentIcon,
  MdShare as ShareIcon,
  MdFileUpload as UploadIcon,
  MdErrorOutline as ErrorIcon,
  MdWarningAmber as WarningIcon,
  MdAdd as AddIcon,
  MdRemove as RemoveIcon,
  MdPerson as PersonIcon,
  MdSettings as SettingsIcon,
  MdLightMode as SunIcon,
  MdDarkMode as MoonIcon,
  MdCardGiftcard as GiftIcon,
  // 카테고리 아이콘 행(디스커버리 #7)
  MdBrush as IllustIcon,
  MdMusicNote as MusicIcon,
  MdVideocam as VtuberIcon,
  MdShoppingBag as GoodsIcon,
  MdSportsEsports as GameIcon,
  MdPhotoCamera as PhotoIcon,
  MdTheaterComedy as CosplayIcon,
  MdEditNote as WritingIcon,
} from "react-icons/md";
