# Generated by Django 5.2.15 on 2026-07-09 04:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section_type', models.CharField(choices=[('usage_rules', '이용 규칙'), ('first_visit_guide', '첫 방문 가이드'), ('operating_hours', '이용 시간'), ('cheki_meaning', '체키 의미'), ('photo_policy', '촬영 범위'), ('prohibited_actions', '금지 행동'), ('principles', '이용 원칙')], max_length=32)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True, default='')),
                ('version', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('published', 'published')], default='draft', max_length=16)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('store_id', models.CharField(default='hatsukoi', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_guide_sections', to='identity.account')),
            ],
            options={
                'ordering': ['display_order', 'section_type'],
                'indexes': [models.Index(fields=['store_id', 'status'], name='visit_guide_store_i_361ada_idx'), models.Index(fields=['status', 'display_order'], name='visit_guide_status_c3412c_idx')],
                'constraints': [models.UniqueConstraint(fields=('store_id', 'section_type'), name='uniq_guide_section_per_type')],
            },
        ),
    ]
