# Generated by Django 6.0.7 on 2026-07-17 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_account_email_account_email_verified_at_and_more'),
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='status',
            field=models.CharField(choices=[('visible', 'visible'), ('taken_down', 'taken_down')], default='visible', max_length=16),
        ),
        migrations.AddIndex(
            model_name='upload',
            index=models.Index(fields=['url'], name='uploads_upl_url_b2bfc6_idx'),
        ),
    ]
