# Generated by Django 6.0.7 on 2026-07-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_upload_status_upload_uploads_upl_url_b2bfc6_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='quarantine_key',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
