# Generated by Django 5.2.15 on 2026-07-09 04:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0001_initial'),
        ('visit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('unwanted_request', 'unwanted_request'), ('private_contact', 'private_contact'), ('external_meeting', 'external_meeting'), ('verbal_abuse', 'verbal_abuse'), ('physical_threat', 'physical_threat'), ('photo_violation', 'photo_violation'), ('stalking_concern', 'stalking_concern'), ('refund_dispute', 'refund_dispute'), ('privacy_portrait_concern', 'privacy_portrait_concern'), ('fraud_abuse', 'fraud_abuse'), ('other', 'other')], max_length=32)),
                ('severity', models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high'), ('critical', 'critical')], max_length=16)),
                ('status', models.CharField(choices=[('received', 'received'), ('reviewing', 'reviewing'), ('actioned', 'actioned'), ('closed', 'closed')], default='received', max_length=16)),
                ('visibility', models.CharField(choices=[('restricted', 'restricted'), ('manager_only', 'manager_only')], default='restricted', max_length=16)),
                ('reporter_type', models.CharField(choices=[('fan', 'fan'), ('cast', 'cast'), ('operator', 'operator'), ('admin', 'admin'), ('unknown', 'unknown')], max_length=16)),
                ('target_type', models.CharField(choices=[('fan', 'fan'), ('cast', 'cast'), ('operator', 'operator'), ('admin', 'admin'), ('unknown', 'unknown')], max_length=16)),
                ('cast_id', models.CharField(blank=True, default='', max_length=64)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_safety_reports', to='identity.account')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='filed_safety_reports', to='identity.account')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='targeted_safety_reports', to='identity.account')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='safety_reports', to='visit.visitrecord')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SafetyReportDetail',
            fields=[
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='detail', serialize=False, to='safety.safetyreport')),
                ('narrative', models.TextField(blank=True, default='')),
                ('resolution_note', models.TextField(blank=True, default='')),
                ('manager_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('block_scope', models.CharField(choices=[('reservation', 'reservation'), ('fandom_feature', 'fandom_feature'), ('store_visit', 'store_visit'), ('all', 'all')], max_length=16)),
                ('block_reason', models.CharField(max_length=255)),
                ('is_risk_flag', models.BooleanField(default=False)),
                ('effective_from', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'active'), ('lifted', 'lifted')], default='active', max_length=16)),
                ('lifted_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_blocks', to='identity.account')),
                ('source_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='blocks', to='safety.safetyreport')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blocks', to='identity.account')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='safetyreport',
            index=models.Index(fields=['status', 'created_at'], name='safety_safe_status_5ad755_idx'),
        ),
        migrations.AddIndex(
            model_name='safetyreport',
            index=models.Index(fields=['severity', 'status'], name='safety_safe_severit_0268ba_idx'),
        ),
        migrations.AddIndex(
            model_name='safetyreport',
            index=models.Index(fields=['report_type'], name='safety_safe_report__160c86_idx'),
        ),
        migrations.AddIndex(
            model_name='userblock',
            index=models.Index(fields=['target', 'status'], name='safety_user_target__19f621_idx'),
        ),
        migrations.AddIndex(
            model_name='userblock',
            index=models.Index(fields=['status', 'effective_from'], name='safety_user_status_28857d_idx'),
        ),
    ]
