# Generated by Django 6.0.7 on 2026-07-17 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0001_initial'),
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='safetyreport',
            name='upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='safety_reports', to='uploads.upload'),
        ),
    ]
