# Generated by Django 5.2.15 on 2026-07-09 04:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('store_id', models.CharField(default='hatsukoi', max_length=64)),
                ('reservation_type', models.CharField(choices=[('reservation', 'reservation'), ('waitlist', 'waitlist')], default='reservation', max_length=16)),
                ('status', models.CharField(choices=[('requested', 'requested'), ('confirmed', 'confirmed'), ('cancelled', 'cancelled'), ('no_show', 'no_show')], default='requested', max_length=16)),
                ('reserved_date', models.DateField()),
                ('reserved_time', models.TimeField(blank=True, null=True)),
                ('party_size', models.PositiveSmallIntegerField(default=1)),
                ('operator_note', models.TextField(blank=True, default='')),
                ('cancellation_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_reservations', to='identity.account')),
                ('fan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='identity.account')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reserved_date'], name='reservation_reserve_5f420d_idx'), models.Index(fields=['fan', '-created_at'], name='reservation_fan_id_4970ee_idx'), models.Index(fields=['status', 'reserved_date'], name='reservation_status_26c777_idx'), models.Index(fields=['store_id', 'reserved_date'], name='reservation_store_i_c13ad6_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['requested', 'confirmed'])), fields=('fan', 'reserved_date', 'reserved_time', 'reservation_type'), name='uniq_active_reservation_slot'), models.UniqueConstraint(condition=models.Q(('reserved_time__isnull', True), ('status__in', ['requested', 'confirmed'])), fields=('fan', 'reserved_date', 'reservation_type'), name='uniq_active_reservation_slot_no_time')],
            },
        ),
    ]
