# Generated by Django 5.2.15 on 2026-07-09 04:52

import apps.commerce.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('creator', '0001_initial'),
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(default=apps.commerce.models._order_code, editable=False, max_length=20, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('paid', 'paid'), ('shipping', 'shipping'), ('completed', 'completed'), ('cancelled', 'cancelled')], default='paid', max_length=16)),
                ('subtotal', models.PositiveIntegerField(default=0)),
                ('shipping_fee', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('recipient_name', models.CharField(blank=True, default='', max_length=60)),
                ('recipient_phone', models.CharField(blank=True, default='', max_length=32)),
                ('postal_code', models.CharField(blank=True, default='', max_length=16)),
                ('address1', models.CharField(blank=True, default='', max_length=200)),
                ('address2', models.CharField(blank=True, default='', max_length=200)),
                ('idempotency_key', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='identity.account')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('goods', 'goods'), ('digital', 'digital'), ('experience', 'experience'), ('ticket', 'ticket'), ('coupon', 'coupon')], max_length=16)),
                ('title', models.CharField(max_length=120)),
                ('price', models.PositiveIntegerField(default=0)),
                ('meta', models.CharField(blank=True, default='', max_length=120)),
                ('media_url', models.CharField(blank=True, default='', max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('stock', models.PositiveIntegerField(blank=True, null=True)),
                ('sold_out', models.BooleanField(default=False)),
                ('locked', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('selling', 'selling'), ('soldout', 'soldout'), ('draft', 'draft'), ('hidden', 'hidden')], default='selling', max_length=16)),
                ('adult_only', models.BooleanField(default=False)),
                ('options', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='creator.creator')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('item_type', models.CharField(choices=[('goods', 'goods'), ('digital', 'digital'), ('experience', 'experience'), ('ticket', 'ticket'), ('coupon', 'coupon')], max_length=16)),
                ('option', models.CharField(blank=True, default='', max_length=120)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('price', models.PositiveIntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='commerce.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='commerce.product')),
            ],
        ),
        migrations.CreateModel(
            name='RefundRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=120)),
                ('detail', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('requested', 'requested'), ('reviewing', 'reviewing'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='requested', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_requests', to='commerce.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['buyer', '-created_at'], name='commerce_or_buyer_i_eb3a07_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('buyer', 'idempotency_key'), name='uniq_order_buyer_idempotency_key'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['creator', '-created_at'], name='commerce_pr_creator_bc614a_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['type'], name='commerce_pr_type_05ddb0_idx'),
        ),
        migrations.AddIndex(
            model_name='refundrequest',
            index=models.Index(fields=['order', '-created_at'], name='commerce_re_order_i_eb80fe_idx'),
        ),
        migrations.AddConstraint(
            model_name='refundrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('requested', 'reviewing'))), fields=('order',), name='uniq_open_refund_per_order'),
        ),
    ]
