# Generated by Django 5.2.15 on 2026-07-11 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_provenance',
            field=models.CharField(choices=[('free', 'free'), ('mock', 'mock'), ('external', 'external'), ('legacy_unknown', 'legacy unknown')], default='legacy_unknown', max_length=16),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_provenance'], name='commerce_or_payment_0bf23c_idx'),
        ),
    ]
