# Generated by Django 5.2.15 on 2026-07-11 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_order_payment_provenance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pricing_kind',
            field=models.CharField(choices=[('paid', 'paid'), ('free', 'free')], default='paid', max_length=8),
        ),
    ]
