# Generated by Django 5.2.15 on 2026-07-09 04:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('creator', '0001_initial'),
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_blocks', to='identity.account')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to='creator.creator')),
            ],
            options={
                'indexes': [models.Index(fields=['blocker', '-created_at'], name='social_crea_blocker_c31ae5_idx')],
                'constraints': [models.UniqueConstraint(fields=('blocker', 'creator'), name='uniq_creatorblock_blocker_creator')],
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='creator.creator')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_set', to='identity.account')),
            ],
            options={
                'indexes': [models.Index(fields=['creator', '-created_at'], name='social_foll_creator_d73ec8_idx'), models.Index(fields=['follower', '-created_at'], name='social_foll_followe_31933d_idx')],
                'constraints': [models.UniqueConstraint(fields=('follower', 'creator'), name='uniq_follow_follower_creator')],
            },
        ),
    ]
