# Generated by Django 5.2.15 on 2026-07-09 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('rule', 'rule'), ('privacy', 'privacy'), ('terms', 'terms'), ('marketing', 'marketing'), ('age', 'age')], max_length=16)),
                ('version', models.CharField(max_length=32)),
                ('given_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_records', to='identity.account')),
            ],
            options={
                'ordering': ['-given_at'],
                'indexes': [models.Index(fields=['account', 'kind'], name='consent_con_account_3d3cc2_idx')],
            },
        ),
    ]
