# Generated by Django 6.0.7 on 2026-07-12 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consent', '0001_initial'),
        ('identity', '0002_account_withdrawn_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('push', 'push'), ('sms', 'sms'), ('email', 'email')], max_length=16)),
                ('enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_consents', to='identity.account')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('account', 'channel'), name='uniq_marketing_channel')],
            },
        ),
    ]
