# Generated by Django 5.2.15 on 2026-07-09 04:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fan_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('role', models.CharField(choices=[('fan', 'fan'), ('cast', 'cast'), ('operator', 'operator'), ('manager', 'manager'), ('admin', 'admin'), ('system', 'system')], default='fan', max_length=16)),
                ('username', models.CharField(blank=True, db_index=True, default='', max_length=150)),
                ('password_hash', models.CharField(blank=True, default='', max_length=256)),
                ('nickname', models.CharField(blank=True, default='', max_length=40)),
                ('auth_method', models.CharField(blank=True, default='', max_length=16)),
                ('auth_subject_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('adult_verified', models.BooleanField(default=False)),
                ('kyc_status', models.CharField(choices=[('unverified', 'unverified'), ('pending', 'pending'), ('verified', 'verified'), ('failed', 'failed')], default='unverified', max_length=16)),
                ('kyc_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('auth_subject_hash', ''), _negated=True), fields=('auth_subject_hash',), name='uniq_fan_auth_subject'), models.UniqueConstraint(condition=models.Q(('username', ''), _negated=True), fields=('username',), name='uniq_staff_username')],
            },
        ),
        migrations.CreateModel(
            name='AnonymousSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonymous_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merged_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_anonymous_sessions', to='identity.account')),
            ],
        ),
        migrations.CreateModel(
            name='TokenFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked', models.BooleanField(default=False)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.CharField(blank=True, default='', max_length=64)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_families', to='identity.account')),
            ],
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to='identity.tokenfamily')),
            ],
        ),
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked', models.BooleanField(default=False)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_tokens', to='identity.tokenfamily')),
            ],
        ),
    ]
