# Generated by Django 6.0.7 on 2026-07-12 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='withdrawn_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
