# Generated by Django 6.0.7 on 2026-07-16 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('membership', '0003_membershiptier_pricing_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='required_tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gated_posts', to='membership.membershiptier'),
        ),
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('public', 'public'), ('members', 'members')], default='public', max_length=8),
        ),
    ]
