# Generated by Django 5.2.15 on 2026-07-09 04:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('event_name', models.CharField(choices=[('fan_signed_up', 'fan_signed_up'), ('anonymous_user_created', 'anonymous_user_created'), ('anonymous_user_merged', 'anonymous_user_merged'), ('rule_consent_given', 'rule_consent_given'), ('reservation_created', 'reservation_created'), ('reservation_cancelled', 'reservation_cancelled'), ('visit_checked_in', 'visit_checked_in'), ('visit_completed', 'visit_completed'), ('visit_invalidated', 'visit_invalidated'), ('cast_profile_viewed', 'cast_profile_viewed'), ('schedule_viewed', 'schedule_viewed'), ('favorite_added', 'favorite_added'), ('favorite_removed', 'favorite_removed'), ('cheki_recorded', 'cheki_recorded'), ('cheki_invalidated', 'cheki_invalidated'), ('event_viewed', 'event_viewed'), ('event_reserved', 'event_reserved'), ('event_reservation_cancelled', 'event_reservation_cancelled'), ('coupon_issued', 'coupon_issued'), ('coupon_redeemed', 'coupon_redeemed'), ('coupon_cancelled', 'coupon_cancelled'), ('coupon_expired', 'coupon_expired'), ('point_granted', 'point_granted'), ('point_adjusted', 'point_adjusted'), ('pos_order_linked', 'pos_order_linked'), ('pos_reconciliation_flagged', 'pos_reconciliation_flagged'), ('payment_refunded', 'payment_refunded'), ('safety_report_created', 'safety_report_created'), ('safety_report_resolved', 'safety_report_resolved'), ('user_blocked', 'user_blocked'), ('admin_note_created', 'admin_note_created')], max_length=64)),
                ('schema_version', models.CharField(default='1.0', max_length=16)),
                ('occurred_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('actor_type', models.CharField(choices=[('fan', 'fan'), ('cast', 'cast'), ('operator', 'operator'), ('admin', 'admin'), ('system', 'system')], max_length=16)),
                ('actor_id', models.CharField(blank=True, default='', max_length=64)),
                ('source', models.CharField(choices=[('fan_app', 'fan_app'), ('web', 'web'), ('admin', 'admin'), ('kiosk', 'kiosk'), ('manual', 'manual'), ('pos_csv', 'pos_csv'), ('pos_api', 'pos_api'), ('pos_webhook', 'pos_webhook'), ('system', 'system')], max_length=16)),
                ('source_system', models.CharField(default='assen_platform', max_length=32)),
                ('fan_id', models.CharField(blank=True, default='', max_length=64)),
                ('cast_id', models.CharField(blank=True, default='', max_length=64)),
                ('visit_id', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('completed', 'completed'), ('cancelled', 'cancelled'), ('refunded', 'refunded'), ('invalidated', 'invalidated'), ('resolved', 'resolved')], default='completed', max_length=16)),
                ('actor_is_operator', models.BooleanField(default=False)),
                ('is_invalidated', models.BooleanField(default=False)),
                ('invalid_reason', models.CharField(blank=True, default='', max_length=255)),
                ('ids', models.JSONField(blank=True, default=dict)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('quality', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['event_name', 'occurred_at'], name='event_log_e_event_n_7e0989_idx'), models.Index(fields=['fan_id'], name='event_log_e_fan_id_5ec204_idx')],
            },
        ),
    ]
