# Generated by Django 5.2.15 on 2026-07-09 04:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0001_initial'),
        ('visit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChekiRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cast_id', models.CharField(max_length=64)),
                ('cheki_type', models.CharField(choices=[('basic', 'basic'), ('option', 'option'), ('event', 'event'), ('comp', 'comp'), ('test', 'test')], max_length=16)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('image_stored', models.BooleanField(default=False)),
                ('consent_scope', models.CharField(blank=True, default='', max_length=32)),
                ('settlement_status', models.CharField(choices=[('candidate', 'candidate'), ('hold', 'hold'), ('excluded', 'excluded')], default='candidate', max_length=16)),
                ('pos_order_id', models.CharField(blank=True, default='', max_length=64)),
                ('pos_receipt_no', models.CharField(blank=True, default='', max_length=64)),
                ('store_id', models.CharField(default='hatsukoi', max_length=64)),
                ('status', models.CharField(choices=[('active', 'active'), ('voided', 'voided')], default='active', max_length=16)),
                ('void_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_cheki_records', to='identity.account')),
                ('fan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cheki_records', to='identity.account')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cheki_records', to='visit.visitrecord')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='cheki_cheki_created_e4cb44_idx'), models.Index(fields=['cast_id', 'created_at'], name='cheki_cheki_cast_id_8c7989_idx'), models.Index(fields=['status', 'created_at'], name='cheki_cheki_status_7794c4_idx'), models.Index(fields=['settlement_status'], name='cheki_cheki_settlem_277335_idx')],
            },
        ),
    ]
