# Generated by Django 5.2.15 on 2026-07-09 04:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('event_type', models.CharField(choices=[('birthday', 'birthday'), ('theme_day', 'theme_day'), ('guest_day', 'guest_day'), ('costume_day', 'costume_day'), ('other', 'other')], default='other', max_length=16)),
                ('store_id', models.CharField(default='hatsukoi', max_length=64)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('notice', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'draft'), ('published', 'published'), ('closed', 'closed')], default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='event_campaigns', to='identity.account')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_event_campaigns', to='identity.account')),
            ],
            options={
                'ordering': ['-starts_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('reserved', 'reserved'), ('waitlisted', 'waitlisted'), ('cancelled', 'cancelled')], default='reserved', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='event_campaign.eventcampaign')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_event_reservations', to='identity.account')),
                ('fan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_reservations', to='identity.account')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='eventcampaign',
            index=models.Index(fields=['status', 'starts_at'], name='event_campa_status_82201c_idx'),
        ),
        migrations.AddIndex(
            model_name='eventcampaign',
            index=models.Index(fields=['store_id', 'starts_at'], name='event_campa_store_i_ef25db_idx'),
        ),
        migrations.AddIndex(
            model_name='eventcampaign',
            index=models.Index(fields=['event_type'], name='event_campa_event_t_1593be_idx'),
        ),
        migrations.AddIndex(
            model_name='eventreservation',
            index=models.Index(fields=['campaign', 'status'], name='event_campa_campaig_ce2034_idx'),
        ),
        migrations.AddIndex(
            model_name='eventreservation',
            index=models.Index(fields=['fan', '-created_at'], name='event_campa_fan_id_e0f679_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventreservation',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['reserved', 'waitlisted'])), fields=('campaign', 'fan'), name='uniq_active_event_reservation'),
        ),
    ]
