# Generated by Django 5.2.15 on 2026-07-09 04:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coupon_type', models.CharField(choices=[('revisit', 'revisit'), ('event', 'event'), ('manual', 'manual'), ('apology', 'apology')], max_length=16)),
                ('status', models.CharField(choices=[('active', 'active'), ('redeemed', 'redeemed'), ('cancelled', 'cancelled'), ('expired', 'expired')], default='active', max_length=16)),
                ('redemption_id', models.UUIDField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('store_id', models.CharField(default='hatsukoi', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coupons', to='identity.account')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_coupons', to='identity.account')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['fan', 'status'], name='coupon_coup_fan_id_7f1729_idx'), models.Index(fields=['status'], name='coupon_coup_status_e375ec_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('redemption_id__isnull', False)), fields=('redemption_id',), name='uniq_coupon_redemption_id')],
            },
        ),
        migrations.CreateModel(
            name='PointEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('delta', models.IntegerField()),
                ('reason', models.CharField(blank=True, default='', max_length=200)),
                ('reference', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_point_entries', to='identity.account')),
                ('fan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='point_entries', to='identity.account')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['fan', '-created_at'], name='coupon_poin_fan_id_6287b5_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('reference', ''), _negated=True), fields=('fan', 'reference'), name='uniq_point_entry_reference')],
            },
        ),
    ]
