# Generated by Django 5.2.15 on 2026-07-11 06:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_order_payment_provenance_and_more'),
        ('membership', '0002_subscription_payment_provenance_and_more'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('mock', 'mock'), ('free', 'free'), ('external', 'external')], max_length=16)),
                ('provider_txn_id', models.CharField(blank=True, default='', max_length=128)),
                ('authorized_amount', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='KRW', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('succeeded', 'succeeded'), ('failed', 'failed'), ('refunded', 'refunded')], default='pending', max_length=16)),
                ('idempotency_key', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_attempts', to='commerce.order')),
                ('original_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to='payments.paymentattempt')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_attempts', to='membership.subscription')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order', '-created_at'], name='payments_pa_order_i_37df30_idx'), models.Index(fields=['subscription', '-created_at'], name='payments_pa_subscri_7a2894_idx'), models.Index(fields=['provider', 'status'], name='payments_pa_provide_681c90_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('order__isnull', False), ('subscription__isnull', True)), models.Q(('order__isnull', True), ('subscription__isnull', False)), _connector='OR'), name='payment_attempt_exactly_one_target')],
            },
        ),
    ]
