# Generated by Django 6.0.7 on 2026-07-12 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0003_product_pricing_kind'),
        ('commerce_bridge', '0001_initial'),
        ('membership', '0003_membershiptier_pricing_kind_and_more'),
        ('payments', '0002_paymentattempt'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='paymentattempt',
            name='payment_attempt_exactly_one_target',
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='external_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_attempts', to='commerce_bridge.externalcommerceorder'),
        ),
        migrations.AddIndex(
            model_name='paymentattempt',
            index=models.Index(fields=['external_order', '-created_at'], name='payments_pa_externa_0979f9_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentattempt',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('external_order__isnull', True), ('order__isnull', False), ('subscription__isnull', True)), models.Q(('external_order__isnull', True), ('order__isnull', True), ('subscription__isnull', False)), models.Q(('external_order__isnull', False), ('order__isnull', True), ('subscription__isnull', True)), _connector='OR'), name='payment_attempt_exactly_one_target'),
        ),
    ]
