# Generated by Django 6.0.7 on 2026-07-16 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_subscription_agreed_period_subscription_agreed_price_and_more'),
        ('payments', '0003_remove_paymentattempt_payment_attempt_exactly_one_target_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentattempt',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_attempts', to='membership.subscription'),
        ),
    ]
