# Generated by Django 6.0.7 on 2026-07-16 08:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_paymentattempt_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReversal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('mock', 'mock'), ('free', 'free'), ('external', 'external')], max_length=16)),
                ('reversal_ref', models.CharField(blank=True, default='', max_length=128)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='KRW', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('succeeded', 'succeeded'), ('failed', 'failed')], default='pending', max_length=16)),
                ('reason', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_attempt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='payments.paymentattempt')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['original_attempt', '-created_at'], name='payments_pa_origina_68e065_idx'), models.Index(fields=['provider', 'status'], name='payments_pa_provide_b7d8f9_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'succeeded')), fields=('original_attempt',), name='uniq_succeeded_reversal_per_attempt')],
            },
        ),
    ]
