# Generated by Django 5.2.15 on 2026-07-09 04:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0001_initial'),
        ('visit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pos_receipt_no', models.CharField(blank=True, default='', max_length=64)),
                ('pos_order_id', models.CharField(blank=True, default='', max_length=64)),
                ('business_day', models.DateField()),
                ('payment_status', models.CharField(choices=[('paid', 'paid'), ('refunded', 'refunded'), ('cancelled', 'cancelled'), ('unpaid', 'unpaid'), ('unknown', 'unknown')], default='unknown', max_length=16)),
                ('payment_method', models.CharField(choices=[('cash', 'cash'), ('card', 'card'), ('transfer', 'transfer'), ('simple_pay', 'simple_pay'), ('mixed', 'mixed'), ('unknown', 'unknown')], default='unknown', max_length=16)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('link_method', models.CharField(choices=[('manual', 'manual'), ('csv_match', 'csv_match'), ('api_match', 'api_match'), ('webhook_match', 'webhook_match')], default='manual', max_length=16)),
                ('linked_confidence', models.CharField(choices=[('exact', 'exact'), ('likely', 'likely'), ('manual', 'manual'), ('unknown', 'unknown')], default='manual', max_length=16)),
                ('pos_vendor_name', models.CharField(blank=True, default='', max_length=64)),
                ('reconciliation_status', models.CharField(choices=[('matched', 'matched'), ('unmatched', 'unmatched'), ('disputed', 'disputed'), ('excluded', 'excluded')], default='unmatched', max_length=16)),
                ('status', models.CharField(choices=[('active', 'active'), ('voided', 'voided')], default='active', max_length=16)),
                ('void_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_pos_orders', to='identity.account')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_orders', to='visit.visitrecord')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business_day'], name='pos_lite_po_busines_84da12_idx'), models.Index(fields=['visit'], name='pos_lite_po_visit_i_b53e05_idx'), models.Index(fields=['status', 'business_day'], name='pos_lite_po_status_0a6292_idx'), models.Index(fields=['reconciliation_status'], name='pos_lite_po_reconci_ede93b_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active'), models.Q(('pos_receipt_no', ''), _negated=True)), fields=('pos_receipt_no',), name='uniq_active_pos_receipt_no')],
            },
        ),
    ]
