# Generated by Django 5.2.15 on 2026-07-09 04:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visited_at', models.DateTimeField()),
                ('store_id', models.CharField(default='hatsukoi', max_length=64)),
                ('status', models.CharField(choices=[('active', 'active'), ('voided', 'voided')], default='active', max_length=16)),
                ('source', models.CharField(choices=[('operator_manual', 'operator_manual'), ('qr_self', 'qr_self')], default='operator_manual', max_length=32)),
                ('note', models.TextField(blank=True, default='')),
                ('void_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_visit_records', to='identity.account')),
                ('fan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visit_records', to='identity.account')),
            ],
            options={
                'ordering': ['-visited_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CheckinToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('fan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkin_tokens', to='identity.account')),
                ('redeemed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='redeemed_checkin_tokens', to='identity.account')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checkin_token', to='visit.visitrecord')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.AddIndex(
            model_name='visitrecord',
            index=models.Index(fields=['visited_at'], name='visit_visit_visited_417a7c_idx'),
        ),
        migrations.AddIndex(
            model_name='visitrecord',
            index=models.Index(fields=['fan', 'visited_at'], name='visit_visit_fan_id_a3bef1_idx'),
        ),
        migrations.AddIndex(
            model_name='visitrecord',
            index=models.Index(fields=['status', 'visited_at'], name='visit_visit_status_de14e0_idx'),
        ),
        migrations.AddIndex(
            model_name='checkintoken',
            index=models.Index(fields=['fan', 'issued_at'], name='visit_check_fan_id_76f5eb_idx'),
        ),
        migrations.AddIndex(
            model_name='checkintoken',
            index=models.Index(fields=['expires_at'], name='visit_check_expires_8e4462_idx'),
        ),
    ]
