# Generated by Django 5.2.15 on 2026-07-09 04:52

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('handle', models.CharField(db_index=True, max_length=32, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9_]+$', 'handle는 소문자·숫자·밑줄(_)만 사용할 수 있습니다.')])),
                ('name', models.CharField(max_length=80)),
                ('bio', models.TextField(blank=True, default='')),
                ('accent_color', models.CharField(blank=True, default='', max_length=9)),
                ('avatar_url', models.CharField(blank=True, default='', max_length=500)),
                ('cover_url', models.CharField(blank=True, default='', max_length=500)),
                ('category', models.CharField(blank=True, default='', max_length=40)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_profile', to='identity.account')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category'], name='creator_cre_categor_24d704_idx'), models.Index(fields=['-created_at'], name='creator_cre_created_23e772_idx')],
            },
        ),
    ]
