# Generated by Django 6.0.7 on 2026-07-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
