# Generated by Django 5.2.15 on 2026-07-09 04:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('work_date', models.DateField()),
                ('cast_id', models.CharField(max_length=64)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('draft', 'draft'), ('published', 'published'), ('unpublished', 'unpublished')], default='draft', max_length=16)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_schedule_entries', to='identity.account')),
            ],
            options={
                'ordering': ['work_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleChangeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proposed', models.JSONField(default=dict)),
                ('before', models.JSONField(default=dict)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=16)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decided_schedule_changes', to='identity.account')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_schedule_changes', to='identity.account')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_requests', to='schedule.scheduleentry')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='scheduleentry',
            index=models.Index(fields=['work_date', 'status'], name='schedule_sc_work_da_42ba53_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduleentry',
            index=models.Index(fields=['cast_id', 'work_date'], name='schedule_sc_cast_id_d3ee8e_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulechangerequest',
            index=models.Index(fields=['status', 'created_at'], name='schedule_sc_status_f6cedc_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulechangerequest',
            index=models.Index(fields=['entry', 'status'], name='schedule_sc_entry_i_e73dd7_idx'),
        ),
    ]
