# Generated by Django 6.0.7 on 2026-07-12 14:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('creator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('cafe24', 'cafe24'), ('imweb', 'imweb'), ('generic', 'generic')], max_length=16)),
                ('external_event_id', models.CharField(max_length=128)),
                ('event_type', models.CharField(max_length=32)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-received_at'],
                'constraints': [models.UniqueConstraint(fields=('provider', 'external_event_id'), name='uniq_webhook_event')],
            },
        ),
        migrations.CreateModel(
            name='ExternalCommerceOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('cafe24', 'cafe24'), ('imweb', 'imweb'), ('generic', 'generic')], max_length=16)),
                ('external_order_id', models.CharField(max_length=128)),
                ('buyer_ref', models.CharField(blank=True, default='', max_length=128)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='KRW', max_length=3)),
                ('status', models.CharField(choices=[('paid', 'paid'), ('shipped', 'shipped'), ('cancelled', 'cancelled'), ('refunded', 'refunded')], max_length=16)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_orders', to='creator.creator')),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['creator', '-received_at'], name='commerce_br_creator_e3cd40_idx'), models.Index(fields=['provider', 'status'], name='commerce_br_provide_182351_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'external_order_id'), name='uniq_external_order')],
            },
        ),
    ]
