# Generated by Django 5.2.15 on 2026-07-09 04:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CastProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage_name', models.CharField(max_length=120)),
                ('intro', models.TextField(blank=True, default='')),
                ('photo_ref', models.CharField(blank=True, default='', max_length=512)),
                ('cheki_available', models.BooleanField(default=False)),
                ('content_scope', models.CharField(blank=True, default='', max_length=255)),
                ('visibility', models.CharField(choices=[('private', 'private'), ('public', 'public')], default='private', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_cast_profiles', to='identity.account')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CastConsent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('stage_name', 'stage_name'), ('profile_photo', 'profile_photo'), ('profile_intro', 'profile_intro'), ('schedule', 'schedule'), ('content_scope', 'content_scope')], max_length=32)),
                ('status', models.CharField(choices=[('withheld', 'withheld'), ('granted', 'granted'), ('refused', 'refused')], default='withheld', max_length=16)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_cast_consents', to='identity.account')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consents', to='cast.castprofile')),
            ],
            options={
                'ordering': ['scope'],
            },
        ),
        migrations.AddIndex(
            model_name='castprofile',
            index=models.Index(fields=['visibility', 'created_at'], name='cast_castpr_visibil_808161_idx'),
        ),
        migrations.AddIndex(
            model_name='castconsent',
            index=models.Index(fields=['profile', 'scope'], name='cast_castco_profile_1896d7_idx'),
        ),
        migrations.AddConstraint(
            model_name='castconsent',
            constraint=models.UniqueConstraint(fields=('profile', 'scope'), name='uniq_cast_consent_profile_scope'),
        ),
    ]
