/// Design token primitives for Assen Platform.
///
/// The authoritative source is `docs/design/tokens.json` (W3C DTCG 2025.10,
/// single source of truth — OQ-11). The raw primitives below are GENERATED by
/// Style Dictionary (`tools/tokens`, ASS-128); regenerate with
/// `dart run melos run codegen`. The semantic colour scheme
/// (`AssenColorScheme`) is the lone hand-written export — an M3-seeded scheme
/// distorts the cream surface, so it is composed from the generated ramp
/// instead (see ADR-0004 and docs/design/tokens.md §3/§7).
library;

// Hand-written semantic mapping (NOT generated — see file header).
export 'src/color_scheme.dart';
// Generated raw primitives (DO NOT EDIT — regenerate from tokens.json).
export 'src/colors.gen.dart';
export 'src/elevation.gen.dart';
export 'src/motion.gen.dart';
export 'src/radius.gen.dart';
export 'src/spacing.gen.dart';
export 'src/theme_extensions.gen.dart';
export 'src/typography.gen.dart';
