# Generated by Django 5.2.15 on 2026-07-09 04:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('creator', '0001_initial'),
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipTier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('price', models.PositiveIntegerField(default=0)),
                ('period', models.CharField(default='월', max_length=8)),
                ('benefits', models.JSONField(default=list)),
                ('badge', models.CharField(blank=True, default='', max_length=20)),
                ('featured', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='creator.creator')),
            ],
            options={
                'ordering': ['sort_order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'active'), ('cancelled', 'cancelled')], default='active', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('next_billing_date', models.DateField()),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fan_subscriptions', to='creator.creator')),
                ('fan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='identity.account')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='membership.membershiptier')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='membershiptier',
            index=models.Index(fields=['creator', 'sort_order'], name='membership__creator_95a918_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['fan', '-started_at'], name='membership__fan_id_fb1c34_idx'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('fan', 'creator'), name='uniq_active_subscription_per_creator'),
        ),
    ]
