# Generated by Django 5.2.15 on 2026-07-11 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_subscription_payment_provenance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiptier',
            name='pricing_kind',
            field=models.CharField(choices=[('paid', 'paid'), ('free', 'free')], default='paid', max_length=8),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='next_billing_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
